ktor:
  application:
    modules:
      - com.fluxo-leve.ApplicationKt.module
  deployment:
    port: 8080
database:
  driverClassName: "org.postgresql.Driver"
  jdbcURL: "jdbc:postgresql://localhost:5432/${POSTGRES_DB}"
  user: "${POSTGRES_USER}"
  password: "${POSTGRES_PASSWORD}"